<?php

// Handy debugging statements:
ini_set('display_errors', 'On');
error_reporting(E_ALL | E_STRICT);

require('db.php');

// This data is generated by app/ReportController.java
$title = (array_key_exists('title', $_POST) ?
             "'" . $_POST['title'] . "'" : 'null');
$description = (array_key_exists('description', $_POST) ?
                "'" . $_POST['description'] . "'" : 'null');
$category = (array_key_exists('category', $_POST['bribe']) ?
             "'" . $_POST['bribe']['category'] . "'" : 'null');
$requested = (array_key_exists('requested', $_POST['bribe']) ?
             $_POST['bribe']['requested'] : "null");
$paid = (array_key_exists('paid', $_POST['bribe']) ?
             $_POST['bribe']['paid'] : "null");
$currency = (array_key_exists('currency', $_POST['bribe']) ?
             "'" . $_POST['bribe']['currency'] . "'" : "null");
$lat = (array_key_exists('lat', $_POST['location']) ?
             $_POST['location']['lat'] : 'null');
$lng = (array_key_exists('lng', $_POST['location']) ?
             $_POST['location']['lng'] : 'null');
$image = (array_key_exists('image_url', $_POST) ?
                "'" . $_POST['image_url'] . "'" : 'null');

echo $lat . "\n";
echo $lng . "\n";
$db = new DaylightDB();
$result = $db->add_report($title, $description, $category, $requested, $paid, $currency, $lat, $lng, $image);
if (FALSE == $result) {
   fail();
}
echo "SUCCESS\n";
exit(0);

function fail() {
   echo "FAILURE\n";
   exit(0);
}
