<?php

// Handy debugging statements:
ini_set('display_errors', 'On');
error_reporting(E_ALL | E_STRICT);

require('db.php');

$db = new DaylightDB();

// This data is generated by app/ReportController.java
$title = (array_key_exists('title', $_POST) ?
             "'" . $db->db->real_escape_string($_POST['title']) . "'" : 'null');
$description = (array_key_exists('description', $_POST) ?
                "'" . $db->db->real_escape_string($_POST['description']) . "'" : 'null');
$category = (array_key_exists('category', $_POST['bribe']) ?
             "'" . $db->db->real_escape_string($_POST['bribe']['category']) . "'" : 'null');
$requested = (array_key_exists('requested', $_POST['bribe']) ?
             $db->db->real_escape_string($_POST['bribe']['requested']) : "null");
$paid = (array_key_exists('paid', $_POST['bribe']) ?
             $db->db->real_escape_string($_POST['bribe']['paid']) : "null");
$currency = (array_key_exists('currency', $_POST['bribe']) ?
             "'" . $db->db->real_escape_string($_POST['bribe']['currency']) . "'" : "null");
$lat = (array_key_exists('lat', $_POST['location']) ?
             $db->db->real_escape_string($_POST['location']['lat']) : 'null');
$lng = (array_key_exists('lng', $_POST['location']) ?
             $db->db->real_escape_string($_POST['location']['lng']) : 'null');
$image = (array_key_exists('image_url', $_POST) ?
                "'" . $db->db->real_escape_string($_POST['image_url']) . "'" : 'null');

/*
echo $title . "\n";
echo $description . "\n";
echo $category . "\n";
echo $requested . "\n";
echo $paid . "\n";
echo $currency . "\n";
echo $lat . "\n";
echo $lng . "\n";
echo $image . "\n";
//*/
$result = $db->add_report($title, $description, $category, $requested, $paid, $currency, $lat, $lng, $image);
if (FALSE == $result) {
   fail();
}
echo "SUCCESS\n";
exit(0);

function fail() {
   echo "FAILURE\n";
   exit(0);
}
