<?php

// Handy debugging statements:
// ini_set('display_errors', 'On');
// error_reporting(E_ALL | E_STRICT);

require('db.php');

// This data is generated by app/ReportController.java

$category = (array_key_exists('category', $_POST) ?
             "'" . $_POST['category'] . "'" : 'null');
$currency_requested = (array_key_exists('currency_requested', $_POST) ?
             "'" . $_POST['currency_requested'] . "'" : "null");
$currency_paid = (array_key_exists('currency_paid', $_POST) ?
             "'" . $_POST['currency_paid'] . "'" : "null");
$bribe_requested = (array_key_exists('bribe_requested', $_POST) ?
             $_POST['bribe_requested'] : "null");
$bribe_paid = (array_key_exists('bribe_paid', $_POST) ?
             $_POST['bribe_paid'] : "null");
$latitude = (array_key_exists('latitude', $_POST) ?
             $_POST['latitude'] : 'null');
$longitude = (array_key_exists('longitude', $_POST) ?
             $_POST['longitude'] : 'null');
$altitude = (array_key_exists('altitude', $_POST) ?
             $_POST['altitude'] : 'null');
$accuracy = (array_key_exists('accuracy', $_POST) ?
             $_POST['accuracy'] : 'null');
$description = (array_key_exists('description', $_POST) ?
                "'" . $_POST['description'] . "'" : 'null');
$official = (array_key_exists('official', $_POST) ?
                "'" . $_POST['official'] . "'" : 'null');

$db = new DaylightDB();
$result = $db->query("INSERT INTO corruption_reports (date, category, currency_requested, currency_paid, bribe_requested, bribe_paid, latitude, longitude, altitude, accuracy, official, description) VALUES (NOW(), $category, $currency_requested, $currency_paid, $bribe_requested, $bribe_paid, $latitude, $longitude, $altitude, $accuracy, $official, $description)");
if (FALSE == $result) {
   fail();
}
echo "SUCCESS\n";
exit(0);

function fail() {
   echo "FAILURE\n";
   exit(0);
}
